config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resource :status
  resource :async_status
  resource :update_status
  resource :searching_user_not_use_index, controller: :searching_user_not_use_index
  resource :searching_user_use_index, controller: :searching_user_use_index
  resource :solved_n_plus_one, controller: :solved_n_plus_one
  resource :unsolved_n_plus_one, controller: :unsolved_n_plus_one
  resource :after_lock_table_of_comments
  resource :locking_in_transaction, controller: :locking_in_transaction

  namespace :api do
    resource :locking_in_transaction, controller: :locking_in_transaction
    resource :get_user_comment, controller: :get_user_comment
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/async_statuses_controller.rb
class AsyncStatusesController < ApplicationController
  def show
    current_status = CurrentStatus.new.execute
    @status = current_status[:status]
    @created_at = current_status[:created_at]
    @notice = flash[:notice]
  end

  def create
    UpdateStatusJob.perform_later
    flash[:notice] = 'queuing!'

    redirect_to action: :show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/solved_n_plus_one_controller.rb
class SolvedNPlusOneController < ApplicationController
  def show
    @users_comments = User.joins(:comments)
                 .select(:name, :comment)
                 .limit(100)
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  def show
    current_status = CurrentStatus.new.execute
    @status = current_status[:status]
    @created_at = current_status[:created_at]
  end

  def create
    update_status = UpdateStatus.new(['ok', 'ng', 'waiting'].sample)
    update_status.execute
    redirect_to action: :show
  end
end

app/controllers/unsolved_n_plus_one_controller.rb
class UnsolvedNPlusOneController < ApplicationController
  def show
    @users = []
    @comments = Comment.offset(rand(1..Comment.count)).limit(100)
    @comments.each do |comment|
      @users << User.find_by(id: comment.user_id)
    end
  end
end

app/controllers/update_statuses_controller.rb
class UpdateStatusesController < ApplicationController
  def show
    update_status = UpdateStatus.new(['ok', 'ng', 'waiting'].shuffle)
    update_status.execute
  end
end

app/helpers/after_lock_table_of_comments_helper.rb
module AfterLockTableOfCommentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/async_statuses_helper.rb
module AsyncStatusesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locking_in_transaction_helper.rb
module LockingInTransactionHelper
end

app/helpers/searching_user_not_use_index_helper.rb
module SearchingUserNotUseIndexHelper
end

app/helpers/searching_user_use_index_helper.rb
module SearchingUserUseIndexHelper
end

app/helpers/solved_n_plus_one_helper.rb
module SolvedNPlusOneHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/unsolved_n_plus_one_helper.rb
module UnsolvedNPlusOneHelper
end

app/helpers/update_statuses_helper.rb
module UpdateStatusesHelper
end

app/views/async_statuses/show.html.erb
<% if @notice.present? %>
  <p><%= @notice %></p>
<% end %>
<p>status: <%= @status %></p>
<p>created_at <%= @created_at %></p>
<%= form_tag async_status_path, method: :post do %>
  <%= submit_tag "update", data: { disable_with: "updating..." }, class: 'pure-button pure-button-primary' %>
<% end %>

app/views/home/index.html.erb
<h1>サンプル一覧</h1>
<ul>
  <li><a href="/locking_in_transaction">database レコードロック</a></li>
</ul>

app/views/solved_n_plus_one/show.html.erb
<p>Solved n plus one</p>

<h1>User comments</h1>
<table class="pure-table">
  <thead>
    <th>name</th>
    <th>comment</th>
  </thead>
  <tbody>
  <% @users_comments.each do |user_comment| %>
    <tr>
      <td><%= user_comment.name %></td>
      <td><%= user_comment.comment %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/statuses/show.html.erb
<p>status: <%= @status %></p>
<p>created_at <%= @created_at %></p>
<%= form_tag status_path, method: :post do %>
  <%= submit_tag "update", data: { disable_with: "updating..." }, class: 'pure-button pure-button-primary' %>
<% end %>

app/views/unsolved_n_plus_one/show.html.erb
<p>Unsolved n plus one</p>

<h1>User comments</h1>
<table class="pure-table">
  <thead>
    <th>name</th>
    <th>comment</th>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= (@comments.select { |c| c.user_id == user.id }).first.comment %></td>
    </tr>
  <% end %>
  </tbody>
</table>